-- Qala Saku schema, consolidated.
--
-- Qala Saku shares a Supabase project (and its auth.users, including Google
-- sign-in) with other apps, so everything lives in its own schema "saku"
-- instead of "public". This file is the final state of the earlier
-- migrations (now in supabase/migrations-legacy, which targeted "public" in
-- the previous project), generated by replaying them into "saku".
--
-- After applying: add "saku" to Dashboard > Project Settings > Data API >
-- Exposed schemas, otherwise the API returns 406 for every query.

-- Function bodies reference tables created further down.
set check_function_bodies = false;

CREATE SCHEMA saku;

CREATE FUNCTION saku.adjust_account_balance_on_opening_update() RETURNS trigger
    LANGUAGE plpgsql
    SET search_path TO 'saku'
    AS $$
begin
  if (NEW.opening_balance <> OLD.opening_balance) then
    NEW.current_balance := NEW.current_balance - OLD.opening_balance + NEW.opening_balance;
  end if;
  return NEW;
end;
$$;

CREATE TABLE saku.savings_goals (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    name text NOT NULL,
    target_amount numeric NOT NULL,
    saved_amount numeric DEFAULT 0 NOT NULL,
    target_date date,
    icon text,
    color text,
    archived boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT savings_goals_name_check CHECK (((char_length(name) >= 1) AND (char_length(name) <= 80))),
    CONSTRAINT savings_goals_saved_amount_check CHECK ((saved_amount >= (0)::numeric)),
    CONSTRAINT savings_goals_target_amount_check CHECK ((target_amount > (0)::numeric))
);

CREATE FUNCTION saku.contribute_savings_goal(goal_id uuid, delta numeric) RETURNS SETOF saku.savings_goals
    LANGUAGE sql
    SET search_path TO 'saku'
    AS $$
  update savings_goals
     set saved_amount = greatest(saved_amount + delta, 0)
   where id = goal_id and user_id = auth.uid()
  returning *;
$$;

CREATE FUNCTION saku.get_total_balance(account_id uuid DEFAULT NULL::uuid) RETURNS numeric
    LANGUAGE sql STABLE SECURITY DEFINER
    SET search_path TO 'saku'
    AS $_$
  select coalesce(sum(a.current_balance), 0)
  from accounts a
  where a.user_id = auth.uid()
    and (($1 is null and a.archived = false) or a.id = $1);
$_$;

CREATE FUNCTION saku.protect_profile_privileged_columns() RETURNS trigger
    LANGUAGE plpgsql
    SET search_path TO 'saku'
    AS $$
begin
  if current_user in ('authenticated', 'anon') then
    if tg_op = 'INSERT' then
      new.plan := 'FREE';
      new.ai_unlimited := false;
      new.live_price_used_at := null;
    else
      new.plan := old.plan;
      new.ai_unlimited := old.ai_unlimited;
      new.live_price_used_at := old.live_price_used_at;
    end if;
  end if;
  return new;
end;
$$;

CREATE FUNCTION saku.report_budget_vs_actual(month_in text, type_in text DEFAULT 'expense'::text) RETURNS TABLE(category_id uuid, category_name text, planned numeric, actual numeric, diff numeric)
    LANGUAGE sql SECURITY DEFINER
    SET search_path TO 'saku'
    AS $$
with me as (
  select auth.uid() as uid
),
planned as (
  select bi.category_id,
         sum(bi.amount)::numeric as planned
  from budgets b
  join me on me.uid = b.user_id
  join budget_items bi on bi.budget_id = b.id
  join categories c on c.id = bi.category_id
  where b.month = month_in
    and c.type::text = type_in
  group by bi.category_id
),
actual as (
  select t.category_id,
         sum(t.amount)::numeric as actual
  from transactions t
  join me on me.uid = t.user_id
  join categories c on c.id = t.category_id
  where t.type::text = type_in
    and t.category_id is not null
    and t.budget_month = month_in
  group by t.category_id
)
select
  coalesce(p.category_id, a.category_id) as category_id,
  (select c.name from categories c where c.id = coalesce(p.category_id, a.category_id)) as category_name,
  coalesce(p.planned, 0)::numeric as planned,
  coalesce(a.actual, 0)::numeric as actual,
  (coalesce(p.planned, 0) - coalesce(a.actual, 0))::numeric as diff
from planned p
full outer join actual a on a.category_id = p.category_id
order by 2 asc;
$$;

CREATE FUNCTION saku.set_account_initial_balance() RETURNS trigger
    LANGUAGE plpgsql
    SET search_path TO 'saku'
    AS $$
begin
  new.current_balance := new.opening_balance;
  return new;
end;
$$;

CREATE FUNCTION saku.update_account_current_balance() RETURNS trigger
    LANGUAGE plpgsql
    SET search_path TO 'saku'
    AS $$
begin
  if (TG_OP = 'INSERT') then
    if (NEW.type = 'income') then
      update accounts set current_balance = current_balance + NEW.amount where id = NEW.account_id;
    elsif (NEW.type = 'expense') then
      update accounts set current_balance = current_balance - NEW.amount where id = NEW.account_id;
    elsif (NEW.type = 'transfer') then
      update accounts set current_balance = current_balance - NEW.amount where id = NEW.from_account_id;
      update accounts set current_balance = current_balance + NEW.amount where id = NEW.to_account_id;
    end if;
    return NEW;
  elsif (TG_OP = 'UPDATE') then
    -- revert old values
    if (OLD.type = 'income') then
      update accounts set current_balance = current_balance - OLD.amount where id = OLD.account_id;
    elsif (OLD.type = 'expense') then
      update accounts set current_balance = current_balance + OLD.amount where id = OLD.account_id;
    elsif (OLD.type = 'transfer') then
      update accounts set current_balance = current_balance + OLD.amount where id = OLD.from_account_id;
      update accounts set current_balance = current_balance - OLD.amount where id = OLD.to_account_id;
    end if;
    -- apply new values
    if (NEW.type = 'income') then
      update accounts set current_balance = current_balance + NEW.amount where id = NEW.account_id;
    elsif (NEW.type = 'expense') then
      update accounts set current_balance = current_balance - NEW.amount where id = NEW.account_id;
    elsif (NEW.type = 'transfer') then
      update accounts set current_balance = current_balance - NEW.amount where id = NEW.from_account_id;
      update accounts set current_balance = current_balance + NEW.amount where id = NEW.to_account_id;
    end if;
    return NEW;
  elsif (TG_OP = 'DELETE') then
    if (OLD.type = 'income') then
      update accounts set current_balance = current_balance - OLD.amount where id = OLD.account_id;
    elsif (OLD.type = 'expense') then
      update accounts set current_balance = current_balance + OLD.amount where id = OLD.account_id;
    elsif (OLD.type = 'transfer') then
      update accounts set current_balance = current_balance + OLD.amount where id = OLD.from_account_id;
      update accounts set current_balance = current_balance - OLD.amount where id = OLD.to_account_id;
    end if;
    return OLD;
  end if;
  return NEW;
end;
$$;

CREATE FUNCTION saku.update_updated_at_column() RETURNS trigger
    LANGUAGE plpgsql
    SET search_path TO 'saku'
    AS $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

CREATE TABLE saku.accounts (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    name text NOT NULL,
    type text NOT NULL,
    currency text DEFAULT 'IDR'::text NOT NULL,
    opening_balance numeric DEFAULT 0 NOT NULL,
    archived boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    account_number text,
    current_balance numeric DEFAULT 0 NOT NULL,
    CONSTRAINT accounts_type_check CHECK ((type = ANY (ARRAY['bank'::text, 'ewallet'::text, 'cash'::text])))
);

CREATE TABLE saku.ai_logs (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    email text NOT NULL,
    feature text NOT NULL,
    created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE saku.budget_items (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    budget_id uuid NOT NULL,
    category_id uuid NOT NULL,
    amount numeric NOT NULL,
    rollover boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE saku.budgets (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    month text NOT NULL,
    total_amount numeric DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE saku.categories (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    name text NOT NULL,
    type text NOT NULL,
    color text,
    icon text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT categories_type_check CHECK ((type = ANY (ARRAY['expense'::text, 'income'::text])))
);

CREATE TABLE saku.payments (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    order_id text NOT NULL,
    product_name text NOT NULL,
    amount integer NOT NULL,
    status text DEFAULT 'pending'::text NOT NULL,
    token text NOT NULL,
    created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE saku.profiles (
    id uuid NOT NULL,
    email text NOT NULL,
    name text NOT NULL,
    default_currency text DEFAULT 'IDR'::text NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    plan text DEFAULT 'FREE'::text NOT NULL,
    live_price_used_at timestamp with time zone,
    onboarding_completed boolean DEFAULT false NOT NULL,
    ai_unlimited boolean DEFAULT false NOT NULL,
    CONSTRAINT profiles_plan_check CHECK ((plan = ANY (ARRAY['FREE'::text, 'PRO'::text])))
);

CREATE TABLE saku.recurring_transactions (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    type text NOT NULL,
    account_id uuid,
    from_account_id uuid,
    to_account_id uuid,
    category_id uuid,
    amount numeric NOT NULL,
    note text DEFAULT ''::text NOT NULL,
    frequency text NOT NULL,
    day_of_month smallint,
    start_date date NOT NULL,
    next_date date NOT NULL,
    end_date date,
    active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT recurring_transactions_amount_check CHECK ((amount > (0)::numeric)),
    CONSTRAINT recurring_transactions_check CHECK ((((type = 'transfer'::text) AND (from_account_id IS NOT NULL) AND (to_account_id IS NOT NULL) AND (from_account_id <> to_account_id) AND (account_id IS NULL) AND (category_id IS NULL)) OR ((type <> 'transfer'::text) AND (account_id IS NOT NULL) AND (from_account_id IS NULL) AND (to_account_id IS NULL)))),
    CONSTRAINT recurring_transactions_check1 CHECK (((frequency = 'weekly'::text) OR (day_of_month IS NOT NULL))),
    CONSTRAINT recurring_transactions_day_of_month_check CHECK (((day_of_month >= 1) AND (day_of_month <= 31))),
    CONSTRAINT recurring_transactions_frequency_check CHECK ((frequency = ANY (ARRAY['weekly'::text, 'monthly'::text]))),
    CONSTRAINT recurring_transactions_type_check CHECK ((type = ANY (ARRAY['expense'::text, 'income'::text, 'transfer'::text])))
);

CREATE TABLE saku.transactions (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    date date NOT NULL,
    type text NOT NULL,
    account_id uuid,
    from_account_id uuid,
    to_account_id uuid,
    amount numeric NOT NULL,
    category_id uuid,
    note text,
    tags text[] DEFAULT '{}'::text[] NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    budget_month text DEFAULT to_char(timezone('utc'::text, now()), 'YYYY-MM'::text) NOT NULL,
    actual_date date DEFAULT (timezone('utc'::text, now()))::date NOT NULL,
    recurring_id uuid,
    CONSTRAINT transactions_type_check CHECK ((type = ANY (ARRAY['expense'::text, 'income'::text, 'transfer'::text])))
);

ALTER TABLE ONLY saku.accounts
    ADD CONSTRAINT accounts_pkey PRIMARY KEY (id);

ALTER TABLE ONLY saku.ai_logs
    ADD CONSTRAINT ai_logs_pkey PRIMARY KEY (id);

ALTER TABLE ONLY saku.budget_items
    ADD CONSTRAINT budget_items_budget_id_category_id_key UNIQUE (budget_id, category_id);

ALTER TABLE ONLY saku.budget_items
    ADD CONSTRAINT budget_items_pkey PRIMARY KEY (id);

ALTER TABLE ONLY saku.budgets
    ADD CONSTRAINT budgets_pkey PRIMARY KEY (id);

ALTER TABLE ONLY saku.budgets
    ADD CONSTRAINT budgets_user_id_month_key UNIQUE (user_id, month);

ALTER TABLE ONLY saku.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);

ALTER TABLE ONLY saku.payments
    ADD CONSTRAINT payments_pkey PRIMARY KEY (id);

ALTER TABLE ONLY saku.profiles
    ADD CONSTRAINT profiles_email_key UNIQUE (email);

ALTER TABLE ONLY saku.profiles
    ADD CONSTRAINT profiles_pkey PRIMARY KEY (id);

ALTER TABLE ONLY saku.recurring_transactions
    ADD CONSTRAINT recurring_transactions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY saku.savings_goals
    ADD CONSTRAINT savings_goals_pkey PRIMARY KEY (id);

ALTER TABLE ONLY saku.transactions
    ADD CONSTRAINT transactions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY saku.transactions
    ADD CONSTRAINT transactions_recurring_occurrence_key UNIQUE (recurring_id, actual_date);

CREATE INDEX accounts_user_id_idx ON saku.accounts USING btree (user_id);

CREATE INDEX ai_logs_email_idx ON saku.ai_logs USING btree (email);

CREATE INDEX ai_logs_feature_idx ON saku.ai_logs USING btree (feature);

CREATE INDEX budget_items_budget_id_idx ON saku.budget_items USING btree (budget_id);

CREATE INDEX budgets_user_id_idx ON saku.budgets USING btree (user_id);

CREATE INDEX categories_user_id_idx ON saku.categories USING btree (user_id);

CREATE UNIQUE INDEX payments_order_id_idx ON saku.payments USING btree (order_id);

CREATE INDEX payments_user_id_idx ON saku.payments USING btree (user_id);

CREATE INDEX recurring_transactions_due_idx ON saku.recurring_transactions USING btree (user_id, next_date) WHERE active;

CREATE INDEX savings_goals_user_id_idx ON saku.savings_goals USING btree (user_id);

CREATE INDEX transactions_user_actual_date_idx ON saku.transactions USING btree (user_id, actual_date);

CREATE INDEX transactions_user_budget_month_idx ON saku.transactions USING btree (user_id, budget_month);

CREATE INDEX transactions_user_id_idx ON saku.transactions USING btree (user_id);

CREATE TRIGGER accounts_adjust_balance_before_update BEFORE UPDATE ON saku.accounts FOR EACH ROW EXECUTE FUNCTION saku.adjust_account_balance_on_opening_update();

CREATE TRIGGER accounts_set_initial_balance BEFORE INSERT ON saku.accounts FOR EACH ROW EXECUTE FUNCTION saku.set_account_initial_balance();

CREATE TRIGGER profiles_protect_privileged_columns BEFORE INSERT OR UPDATE ON saku.profiles FOR EACH ROW EXECUTE FUNCTION saku.protect_profile_privileged_columns();

CREATE TRIGGER transactions_update_account_balance AFTER INSERT OR DELETE OR UPDATE ON saku.transactions FOR EACH ROW EXECUTE FUNCTION saku.update_account_current_balance();

CREATE TRIGGER update_accounts_updated_at BEFORE UPDATE ON saku.accounts FOR EACH ROW EXECUTE FUNCTION saku.update_updated_at_column();

CREATE TRIGGER update_budget_items_updated_at BEFORE UPDATE ON saku.budget_items FOR EACH ROW EXECUTE FUNCTION saku.update_updated_at_column();

CREATE TRIGGER update_budgets_updated_at BEFORE UPDATE ON saku.budgets FOR EACH ROW EXECUTE FUNCTION saku.update_updated_at_column();

CREATE TRIGGER update_categories_updated_at BEFORE UPDATE ON saku.categories FOR EACH ROW EXECUTE FUNCTION saku.update_updated_at_column();

CREATE TRIGGER update_profiles_updated_at BEFORE UPDATE ON saku.profiles FOR EACH ROW EXECUTE FUNCTION saku.update_updated_at_column();

CREATE TRIGGER update_recurring_transactions_updated_at BEFORE UPDATE ON saku.recurring_transactions FOR EACH ROW EXECUTE FUNCTION saku.update_updated_at_column();

CREATE TRIGGER update_savings_goals_updated_at BEFORE UPDATE ON saku.savings_goals FOR EACH ROW EXECUTE FUNCTION saku.update_updated_at_column();

CREATE TRIGGER update_transactions_updated_at BEFORE UPDATE ON saku.transactions FOR EACH ROW EXECUTE FUNCTION saku.update_updated_at_column();

ALTER TABLE ONLY saku.accounts
    ADD CONSTRAINT accounts_user_id_fkey FOREIGN KEY (user_id) REFERENCES saku.profiles(id) ON DELETE CASCADE;

ALTER TABLE ONLY saku.budget_items
    ADD CONSTRAINT budget_items_budget_id_fkey FOREIGN KEY (budget_id) REFERENCES saku.budgets(id) ON DELETE CASCADE;

ALTER TABLE ONLY saku.budget_items
    ADD CONSTRAINT budget_items_category_id_fkey FOREIGN KEY (category_id) REFERENCES saku.categories(id) ON DELETE CASCADE;

ALTER TABLE ONLY saku.budgets
    ADD CONSTRAINT budgets_user_id_fkey FOREIGN KEY (user_id) REFERENCES saku.profiles(id) ON DELETE CASCADE;

ALTER TABLE ONLY saku.categories
    ADD CONSTRAINT categories_user_id_fkey FOREIGN KEY (user_id) REFERENCES saku.profiles(id) ON DELETE CASCADE;

ALTER TABLE ONLY saku.payments
    ADD CONSTRAINT payments_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY saku.profiles
    ADD CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY saku.recurring_transactions
    ADD CONSTRAINT recurring_transactions_account_id_fkey FOREIGN KEY (account_id) REFERENCES saku.accounts(id) ON DELETE CASCADE;

ALTER TABLE ONLY saku.recurring_transactions
    ADD CONSTRAINT recurring_transactions_category_id_fkey FOREIGN KEY (category_id) REFERENCES saku.categories(id) ON DELETE SET NULL;

ALTER TABLE ONLY saku.recurring_transactions
    ADD CONSTRAINT recurring_transactions_from_account_id_fkey FOREIGN KEY (from_account_id) REFERENCES saku.accounts(id) ON DELETE CASCADE;

ALTER TABLE ONLY saku.recurring_transactions
    ADD CONSTRAINT recurring_transactions_to_account_id_fkey FOREIGN KEY (to_account_id) REFERENCES saku.accounts(id) ON DELETE CASCADE;

ALTER TABLE ONLY saku.recurring_transactions
    ADD CONSTRAINT recurring_transactions_user_id_fkey FOREIGN KEY (user_id) REFERENCES saku.profiles(id) ON DELETE CASCADE;

ALTER TABLE ONLY saku.savings_goals
    ADD CONSTRAINT savings_goals_user_id_fkey FOREIGN KEY (user_id) REFERENCES saku.profiles(id) ON DELETE CASCADE;

ALTER TABLE ONLY saku.transactions
    ADD CONSTRAINT transactions_account_id_fkey FOREIGN KEY (account_id) REFERENCES saku.accounts(id);

ALTER TABLE ONLY saku.transactions
    ADD CONSTRAINT transactions_category_id_fkey FOREIGN KEY (category_id) REFERENCES saku.categories(id);

ALTER TABLE ONLY saku.transactions
    ADD CONSTRAINT transactions_from_account_id_fkey FOREIGN KEY (from_account_id) REFERENCES saku.accounts(id);

ALTER TABLE ONLY saku.transactions
    ADD CONSTRAINT transactions_recurring_id_fkey FOREIGN KEY (recurring_id) REFERENCES saku.recurring_transactions(id) ON DELETE SET NULL;

ALTER TABLE ONLY saku.transactions
    ADD CONSTRAINT transactions_to_account_id_fkey FOREIGN KEY (to_account_id) REFERENCES saku.accounts(id);

ALTER TABLE ONLY saku.transactions
    ADD CONSTRAINT transactions_user_id_fkey FOREIGN KEY (user_id) REFERENCES saku.profiles(id) ON DELETE CASCADE;

CREATE POLICY "AI logs are insertable by owner" ON saku.ai_logs FOR INSERT WITH CHECK (((auth.jwt() ->> 'email'::text) = email));

CREATE POLICY "AI logs are readable by owner" ON saku.ai_logs FOR SELECT USING (((auth.jwt() ->> 'email'::text) = email));

CREATE POLICY "Accounts are accessible by owner" ON saku.accounts USING ((user_id = auth.uid())) WITH CHECK ((user_id = auth.uid()));

CREATE POLICY "Budget items are accessible by owner" ON saku.budget_items USING ((EXISTS ( SELECT 1
   FROM saku.budgets b
  WHERE ((b.id = budget_items.budget_id) AND (b.user_id = auth.uid()))))) WITH CHECK ((EXISTS ( SELECT 1
   FROM saku.budgets b
  WHERE ((b.id = budget_items.budget_id) AND (b.user_id = auth.uid())))));

CREATE POLICY "Budgets are accessible by owner" ON saku.budgets USING ((user_id = auth.uid())) WITH CHECK ((user_id = auth.uid()));

CREATE POLICY "Categories are accessible by owner" ON saku.categories USING ((user_id = auth.uid())) WITH CHECK ((user_id = auth.uid()));

CREATE POLICY "Payments are readable by owner" ON saku.payments FOR SELECT USING ((user_id = auth.uid()));

CREATE POLICY "Profiles are accessible by owner" ON saku.profiles USING ((id = auth.uid())) WITH CHECK ((id = auth.uid()));

CREATE POLICY "Recurring transactions are accessible by owner" ON saku.recurring_transactions USING ((user_id = auth.uid())) WITH CHECK ((user_id = auth.uid()));

CREATE POLICY "Savings goals are accessible by owner" ON saku.savings_goals USING ((user_id = auth.uid())) WITH CHECK ((user_id = auth.uid()));

CREATE POLICY "Transactions are accessible by owner" ON saku.transactions USING ((user_id = auth.uid())) WITH CHECK ((user_id = auth.uid()));

ALTER TABLE saku.accounts ENABLE ROW LEVEL SECURITY;

ALTER TABLE saku.ai_logs ENABLE ROW LEVEL SECURITY;

ALTER TABLE saku.budget_items ENABLE ROW LEVEL SECURITY;

ALTER TABLE saku.budgets ENABLE ROW LEVEL SECURITY;

ALTER TABLE saku.categories ENABLE ROW LEVEL SECURITY;

ALTER TABLE saku.payments ENABLE ROW LEVEL SECURITY;

ALTER TABLE saku.profiles ENABLE ROW LEVEL SECURITY;

ALTER TABLE saku.recurring_transactions ENABLE ROW LEVEL SECURITY;

ALTER TABLE saku.savings_goals ENABLE ROW LEVEL SECURITY;

ALTER TABLE saku.transactions ENABLE ROW LEVEL SECURITY;

-- API access. RLS policies above still decide which rows each user sees.
grant usage on schema saku to anon, authenticated, service_role;
grant select, insert, update, delete on all tables in schema saku to authenticated;
grant all on all tables in schema saku to service_role;
revoke execute on all functions in schema saku from public;
grant execute on all functions in schema saku to authenticated, service_role;
alter default privileges in schema saku grant select, insert, update, delete on tables to authenticated;
alter default privileges in schema saku grant all on tables to service_role;
alter default privileges in schema saku revoke execute on functions from public;
alter default privileges in schema saku grant execute on functions to authenticated, service_role;
